package Prakt1

fun main() {
    println("***** Завдання №1 ******")
    val task1 = Task1()
    println(task1.even_odd(6))
    println(task1.even_odd(1005))
    println("***** Завдання №2 ******")
    val task2 = Task2()
    println(task2.PrimarySum())
    println("***** Завдання №3 ******")
    val task3 = Task3()
    println(task3.SumOnes(6))
    println("***** Завдання №4 ******")
    val task4 = Task4()
    println(task4.Fibonnachi(10))
    println("***** Завдання №5 ******")
val task5 = Task5()
    println(task5.Reverse("Fuck"))
    println("***** Завдання №6 ******")
    val task6 = Task6()
    println(task6.Factorial(6))
    println("***** Завдання №7 ******")
    val task7 = Task7()
    println(task7.getJsonOutput("Kotlin"))
    println("***** Завдання №8 ******")
    val task8 = Task8()
    val numbers = listOf(1,6,-105,-15,92,55)
    println(task8.FindMinimal(numbers))
    println("***** Завдання №9 ******")
    val task9 = Task9()
    println(task9.isPolidrom("Radar"))
    println(task9.isPolidrom("Java"))
    println(task9.isPolidrom("A man a plan a canal Panama"))
    println("***** Завдання №10 ******")
    val task10 = Task10()
    println(task10.Ceasar("kotlin the bezt!", 2))

}